[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["samsnyk <samuel.dahlberg@snyk.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"